// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recruitment.API.Data;

#nullable disable

namespace Recruitment.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251223145654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Recruitment.API.Models.Application", b =>
                {
                    b.Property<int>("application_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("applied_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("candidate_id")
                        .HasColumnType("int");

                    b.Property<int>("job_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("joining_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("application_id");

                    b.HasIndex("candidate_id");

                    b.HasIndex("job_id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Recruitment.API.Models.ApplicationComment", b =>
                {
                    b.Property<int>("comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("application_id")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("comment_id");

                    b.HasIndex("user_id");

                    b.ToTable("Application_Comments");
                });

            modelBuilder.Entity("Recruitment.API.Models.Candidate", b =>
                {
                    b.Property<int>("candidate_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("college_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("created_by_user_id")
                        .HasColumnType("int");

                    b.Property<string>("cv_path")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .HasColumnType("longtext");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("candidate_id");

                    b.HasIndex("created_by_user_id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Recruitment.API.Models.CandidateDocument", b =>
                {
                    b.Property<int>("document_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("application_id")
                        .HasColumnType("int");

                    b.Property<string>("document_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("file_path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("uploaded_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("uploaded_by_user_id")
                        .HasColumnType("int");

                    b.Property<string>("verification_status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("document_id");

                    b.HasIndex("application_id");

                    b.HasIndex("uploaded_by_user_id");

                    b.ToTable("Candidate_Documents");
                });

            modelBuilder.Entity("Recruitment.API.Models.Interview", b =>
                {
                    b.Property<int>("interview_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("application_id")
                        .HasColumnType("int");

                    b.Property<string>("interview_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("meeting_link")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("round_number")
                        .HasColumnType("int");

                    b.Property<DateTime?>("scheduled_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("interview_id");

                    b.HasIndex("application_id");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("Recruitment.API.Models.InterviewFeedback", b =>
                {
                    b.Property<int>("feedback_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("comments")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("interview_id")
                        .HasColumnType("int");

                    b.Property<int>("interviewer_user_id")
                        .HasColumnType("int");

                    b.Property<int?>("rating")
                        .HasColumnType("int");

                    b.Property<string>("recommendation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("submitted_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("feedback_id");

                    b.HasIndex("interview_id");

                    b.HasIndex("interviewer_user_id");

                    b.ToTable("Interview_Feedback");
                });

            modelBuilder.Entity("Recruitment.API.Models.InterviewPanel", b =>
                {
                    b.Property<int>("interview_panel_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("interview_id")
                        .HasColumnType("int");

                    b.Property<int>("interviewer_user_id")
                        .HasColumnType("int");

                    b.HasKey("interview_panel_id");

                    b.HasIndex("interview_id");

                    b.HasIndex("interviewer_user_id");

                    b.ToTable("Interview_Panel");
                });

            modelBuilder.Entity("Recruitment.API.Models.Job", b =>
                {
                    b.Property<int>("job_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("created_by_user_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status_reason")
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("job_id");

                    b.HasIndex("created_by_user_id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Recruitment.API.Models.JobInterviewer", b =>
                {
                    b.Property<int>("job_interviewer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("interviewer_user_id")
                        .HasColumnType("int");

                    b.Property<int>("job_id")
                        .HasColumnType("int");

                    b.HasKey("job_interviewer_id");

                    b.HasIndex("interviewer_user_id");

                    b.HasIndex("job_id");

                    b.ToTable("Job_Interviewers");
                });

            modelBuilder.Entity("Recruitment.API.Models.JobReviewer", b =>
                {
                    b.Property<int>("job_reviewer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("job_id")
                        .HasColumnType("int");

                    b.Property<int>("reviewer_user_id")
                        .HasColumnType("int");

                    b.HasKey("job_reviewer_id");

                    b.HasIndex("job_id");

                    b.HasIndex("reviewer_user_id");

                    b.ToTable("Job_Reviewers");
                });

            modelBuilder.Entity("Recruitment.API.Models.JobSkill", b =>
                {
                    b.Property<int>("job_skill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("is_required")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("job_id")
                        .HasColumnType("int");

                    b.Property<int>("skill_id")
                        .HasColumnType("int");

                    b.HasKey("job_skill_id");

                    b.HasIndex("job_id");

                    b.HasIndex("skill_id");

                    b.ToTable("Job_Skills");
                });

            modelBuilder.Entity("Recruitment.API.Models.Role", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Recruitment.API.Models.Skill", b =>
                {
                    b.Property<int>("skill_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("skill_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("skill_id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Recruitment.API.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("otp_code")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("otp_expiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("user_id");

                    b.HasIndex("role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Recruitment.API.Models.Application", b =>
                {
                    b.HasOne("Recruitment.API.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("candidate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.API.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Recruitment.API.Models.ApplicationComment", b =>
                {
                    b.HasOne("Recruitment.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recruitment.API.Models.Candidate", b =>
                {
                    b.HasOne("Recruitment.API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("created_by_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Recruitment.API.Models.CandidateDocument", b =>
                {
                    b.HasOne("Recruitment.API.Models.Application", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("application_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.API.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("uploaded_by_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Recruitment.API.Models.Interview", b =>
                {
                    b.HasOne("Recruitment.API.Models.Application", "Application")
                        .WithMany("Interviews")
                        .HasForeignKey("application_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Recruitment.API.Models.InterviewFeedback", b =>
                {
                    b.HasOne("Recruitment.API.Models.Interview", "Interview")
                        .WithMany()
                        .HasForeignKey("interview_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.API.Models.User", "Interviewer")
                        .WithMany()
                        .HasForeignKey("interviewer_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interview");

                    b.Navigation("Interviewer");
                });

            modelBuilder.Entity("Recruitment.API.Models.InterviewPanel", b =>
                {
                    b.HasOne("Recruitment.API.Models.Interview", "Interview")
                        .WithMany("PanelMembers")
                        .HasForeignKey("interview_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.API.Models.User", "Interviewer")
                        .WithMany()
                        .HasForeignKey("interviewer_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interview");

                    b.Navigation("Interviewer");
                });

            modelBuilder.Entity("Recruitment.API.Models.Job", b =>
                {
                    b.HasOne("Recruitment.API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("created_by_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Recruitment.API.Models.JobInterviewer", b =>
                {
                    b.HasOne("Recruitment.API.Models.User", "Interviewer")
                        .WithMany()
                        .HasForeignKey("interviewer_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.API.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interviewer");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Recruitment.API.Models.JobReviewer", b =>
                {
                    b.HasOne("Recruitment.API.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.API.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("reviewer_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Recruitment.API.Models.JobSkill", b =>
                {
                    b.HasOne("Recruitment.API.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recruitment.API.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("skill_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Recruitment.API.Models.User", b =>
                {
                    b.HasOne("Recruitment.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Recruitment.API.Models.Application", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("Recruitment.API.Models.Interview", b =>
                {
                    b.Navigation("PanelMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
